<?php

return array (
    'ID' => 0,
    'SORT' => 500,
    'MULTIPLE' => 'N',
    'IS_REQUIRED' => 'N',
    'ACTIVE' => 'Y',
    'USER_TYPE' => false,
    'PROPERTY_TYPE' => 'L',
    'FILE_TYPE' => '',
    'LIST_TYPE' => 'L',
    'ROW_COUNT' => 1,
    'COL_COUNT' => 30,
    'LINK_IBLOCK_ID' => 0,
    'DEFAULT_VALUE' => '',
    'USER_TYPE_SETTINGS' => false,
    'WITH_DESCRIPTION' => 'N',
    'SEARCHABLE' => 'N',
    'FILTRABLE' => 'N',
    'MULTIPLE_CNT' => 5,
    'HINT' => '',
    'SECTION_PROPERTY' => 'Y',
    'SMART_FILTER' => 'N',
    'DISPLAY_TYPE' => 'K',
    'DISPLAY_EXPANDED' => 'N',
    'FILTER_HINT' => '',
);